name: mahatacast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  avatar_glow: ^3.0.1
  bloc: ^8.1.4
  bot_toast: ^4.1.3
  dartz: ^0.10.1
  file_picker: ^8.0.3
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.5
  flutter_downloader: ^1.11.7
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.1.2
  flutter_screenutil: ^5.9.0
  flutter_sound: ^9.4.6
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  intl: 
  lottie: ^3.1.0
  open_file: ^3.3.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  flutter_localizations:
      sdk: flutter
  provider: ^6.1.2
  audioplayers: ^6.0.0
  awesome_notifications: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appIcon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/appIcon.png"

flutter:
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
    - family: Orbiton
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
    - family: Janna
      fonts:
        - asset: assets/fonts/Janna-LT-Bold.ttf
    - family: Cairo
      fonts:
        - asset:  assets/fonts/Cairo-VariableFont_slnt,wght.ttf
  uses-material-design: true
  assets:
    - assets/icons/home/
    - assets/icons/auth/
    - assets/icons/explore/
    - assets/icons/library/
    - assets/icons/profile/
    - assets/images/
    - assets/images/animation/Animation.json
    - assets/audio/
flutter_intl:
  enabled: true
