// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnIMwrfuvK0RXWvNKOhPV1Vs99WkmaDw4',
    appId: '1:752690289513:android:bbb671bb2d8e77181c7bf8',
    messagingSenderId: '752690289513',
    projectId: 'podcastapp-2ea5a',
    storageBucket: 'podcastapp-2ea5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmLSlVs813kRradtVO7HS0nX5y3nNLw9Q',
    appId: '1:752690289513:ios:ff882212a4c9806b1c7bf8',
    messagingSenderId: '752690289513',
    projectId: 'podcastapp-2ea5a',
    storageBucket: 'podcastapp-2ea5a.appspot.com',
    iosBundleId: 'com.example.mahatacast',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDAr6GFtA_fv3w2LjVEtH_VGUdhHTzxzI',
    appId: '1:752690289513:web:88ad698800de1f241c7bf8',
    messagingSenderId: '752690289513',
    projectId: 'podcastapp-2ea5a',
    authDomain: 'podcastapp-2ea5a.firebaseapp.com',
    storageBucket: 'podcastapp-2ea5a.appspot.com',
    measurementId: 'G-2PXBQY1C47',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmLSlVs813kRradtVO7HS0nX5y3nNLw9Q',
    appId: '1:752690289513:ios:ff882212a4c9806b1c7bf8',
    messagingSenderId: '752690289513',
    projectId: 'podcastapp-2ea5a',
    storageBucket: 'podcastapp-2ea5a.appspot.com',
    iosBundleId: 'com.example.mahatacast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDAr6GFtA_fv3w2LjVEtH_VGUdhHTzxzI',
    appId: '1:752690289513:web:d7e4ec39908608351c7bf8',
    messagingSenderId: '752690289513',
    projectId: 'podcastapp-2ea5a',
    authDomain: 'podcastapp-2ea5a.firebaseapp.com',
    storageBucket: 'podcastapp-2ea5a.appspot.com',
    measurementId: 'G-90B6823N87',
  );
}